### ISSUE TITLE
Workbench keine Fortschritt

### ISSUE THREAD

**Issue by krakel** [Nedelosk/Modular-Machines#15]
In der Workbench wird kein Fortschrittsbalken im Interface angezeigt.

**Comment by Nedelosk** [comment]
Arbeite daran kommt in der nächsten Version. :)

**Comment by Nedelosk** [comment]
![2015-11-25_22 23 33](https://cloud.githubusercontent.com/assets/10259214/11409871/33ea8438-93c3-11e5-9c71-abf37a9e1f9b.png)
