### ISSUE TITLE
Workbench kein Shift-Klick

### ISSUE THREAD

**Issue by krakel** [Nedelosk/Modular-Machines#16]
Die Workbench läßt sich nicht mit Shift Klick befüllen.

**Comment by Nedelosk** [comment]
Arbeite daran kommt in der nächsten Version. :)

**Comment by krakel** [comment]
Geht immer noch nicht. Auch nicht beim Lagerfeuer.

**Comment by Nedelosk** [comment]
Liegt daran das in unserem modpack noch keine neue Version von forest mods ist.
