### ISSUE TITLE
Wood Gear nicht als Form für Gear Cast

### ISSUE THREAD

**Issue by krakel** [Nedelosk/Modular-Machines#18]
Man kann das Wood Gear nicht als Basis zum Gießen des Gear Cast von Tinker benutzen.

**Comment by krakel** [comment]
Könntest du bitte beim Schließen mit rein schreiben, was du getan hast. (Will doch nicht dumm sterben) :)

**Comment by Nedelosk** [comment]
Nichts aber Holz + Metal != Gut

**Comment by krakel** [comment]
Man muß das Cast aber irgendwie gießen. Allerdeings wenn das Stone Gear wieder geht, muß es halt dann damit sein.

P.S. Dieser Hinweis zum Abweisen des Post war schon hilfreich. Aber so ohne Kommentar zu schließen macht immer so grummelig.
