### ISSUE TITLE
Stone Curbs allein produziert unsichbaren Block

### ISSUE THREAD

**Issue by krakel** [Nedelosk/Modular-Machines#20]
Ich habe ausversehen einen Stone Corbs allein auf den Boden gesetzt. Da ist kurz ein Stone Pot zu sehen, danch ist da nur noch ein Luftblock mit Rand zu sehen. Der Tooltip sagt Campfire. Wenn man das abbaut ist dann alles weg.

**Comment by Nedelosk** [comment]
Schon gefixt : 
![2015-10-29_21 26 47](https://cloud.githubusercontent.com/assets/10259214/10831148/246356c4-7e84-11e5-8a4f-ceaae33894ca.png)
