### ISSUE TITLE
Campfire Waila Progress Tooltip

### ISSUE THREAD

**Issue by DerOliDE** [Nedelosk/Modular-Machines#21]
Progress Zahlen vertauscht es müsste 4 / 10 statt 10 / 4 heißen.

![fd-campfire-progress](https://cloud.githubusercontent.com/assets/5699429/10849899/418743ba-7f23-11e5-9b51-1770ed67b088.jpg)

**Comment by DerOliDE** [comment]
P.S.: Für eine Prozent anzeige wäre es dann x / 10 \* 100 ;-) bzw. gekürzt x \* 10.

**Comment by Nedelosk** [comment]
Schon gefixt ist in dropbox forest-mods-1.7.10-0.3.2e-beta
