### ISSUE TITLE
Auf einem Server keine Synchronisierung zwischen Spielern

### ISSUE THREAD

**Issue by krakel** [Nedelosk/Modular-Machines#24]
Wenn auf dem Server einer einen Holzkohle Stapel anzündet, ändert sich für den anderen die Darstellung nicht.

**Comment by krakel** [comment]
Es scheint auch das Abbrennen des Hügles nicht mehr zu funktionieren. Auf dem Server wandelt er sich nicht in Holzkohle um und wie ich gerade höre auch im Singleplayer nicht.

**Comment by krakel** [comment]
Noch etwas, nach einem Relogg wird keiner der Hügel korrekt angezeigt. Man sieht nur die Holzstapel.

**Comment by krakel** [comment]
In meinem Singleplayer funktioniert die Umwandlung.

**Comment by krakel** [comment]
Es sieht so aus, das alles was mit einer Torch angezündet wird, nicht abbrennt. Alles mit Fint and Steel funtioniert, aber nur im Singleplayer.
Edit:
Habe jetzt auch auf dem Server ordentlichen Abbrand mit Flint and Steel.

**Comment by Nedelosk** [comment]
Arbeite daran kommt in der nächsten Version. :)

**Comment by Nedelosk** [comment]
Müssen wir dann mal auf dem Server Testen
