### ISSUE TITLE
Tinker's Casting Table Not Working When MM Is Installed

### ISSUE THREAD

**Issue by Darkosto** [Nedelosk/Modular-Machines#30]
Hello!

Tinker's Construct smelteries do not cast fluids into an Ingot cast when Modular Machines is installed. The recipes are listed in JEI as if they should work, but do not actually cast. The remaining casts (swords, tool rods, etc.) all work correctly. On removal of MM, the casts all worked as intended. Could you please take a look?

MC Version: 1.10.2
Forge Version: 2089
Mod Version: 1.5.0.97
Tinkers' Version: 2.5.1
Mantle Version: 1.0.0

Thank you! :)
Darkosto

**Comment by meelock** [comment]
I have been having a similar issue with the stencil table, but idk how this mod would be messing with both/either.

**Comment by meelock** [comment]
I have the log over [here](https://github.com/SlimeKnights/TinkersConstruct/issues/2391)

**Comment by meelock** [comment]
confirmed it is the case... what the... i don't even know...

**Comment by meelock** [comment]
welp

**Comment by Nedelosk** [comment]
I can't reproduce this. It works on my client.

**Comment by meelock** [comment]
welp, weird stuff happens with a experimental pack...

**Comment by meelock** [comment]
still having the issue.

**Comment by mjctechguy** [comment]
I just tried it with Tinker Construct and this mod and it works fiine

**Comment by Kashdeya** [comment]
I had the same problem,
